cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: /* access key */
      secret-key: /* secret key */
      
      
server:
  port: 8443     